<?xml version="1.0"?>

<!--
// Copyright 2022 Stereolabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<robot name="stereolabs_camera" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find zed2i_ros2_description)/model/materials.urdf.xacro" />

    <xacro:property name="M_PI"     value="3.1415926535897931" />
    <xacro:property name="zed2i_mesh" value="package://zed2i_ros2_description/meshes/zed2i.stl" />

    <xacro:arg name="camera_name"   default="zed2i" />
    <xacro:arg name="camera_model"  default="zed2i" />
    <xacro:arg name="custom_baseline"  default="0.0" />
    <!-- If GNSS fusion is enabled the position of the antenna with respect to the camera mount point is required -->
    <xacro:arg name="enable_gnss"   default="false" />
    <xacro:arg name="gnss_x" default="0.0" />
    <xacro:arg name="gnss_y" default="0.0" />
    <xacro:arg name="gnss_z" default="0.0" />

    <xacro:property name="baseline" value="0.12" />
    <xacro:property name="height" value="0.03" />
    <xacro:property name="bottom_slope" value="0.0" />
    <xacro:property name="screw_offset_x" value="-0.01" />
    <xacro:property name="screw_offset_z" value="0.0" />
    <xacro:property name="optical_offset_x" value="-0.01" />

    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="$(arg camera_name)_camera_link" />

    <!-- Camera Center -->
    <link name="$(arg camera_name)_camera_center">
        <visual>
            <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://zed2i_ros2_description/meshes/zed2i.stl" />
            </geometry>
            <material name="$(arg camera_model)_mat" />
        </visual>      
        <collision>
            <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://zed2i_ros2_description/meshes/zed2i.stl" />
            </geometry>
        </collision>
    </link>
    <joint name="$(arg camera_name)_camera_center_joint" type="fixed">
      <parent link="$(arg camera_name)_camera_link"/>
      <child link="$(arg camera_name)_camera_center"/>
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>


    <!-- Left Camera -->
    <link name="$(arg camera_name)_left_camera_frame">
    </link>
    <joint name="$(arg camera_name)_left_camera_joint" type="fixed">
        <parent link="$(arg camera_name)_camera_center"/>
        <child link="$(arg camera_name)_left_camera_frame"/>
        <origin xyz="${optical_offset_x} ${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="$(arg camera_name)_left_camera_optical_frame"/>
    <joint name="$(arg camera_name)_left_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="$(arg camera_name)_left_camera_frame"/>
        <child link="$(arg camera_name)_left_camera_optical_frame"/>
    </joint>


    <!-- Right Camera -->
    <link name="$(arg camera_name)_right_camera_frame">
    </link>
    <joint name="$(arg camera_name)_right_camera_joint" type="fixed">
        <parent link="$(arg camera_name)_camera_center"/>
        <child link="$(arg camera_name)_right_camera_frame"/>
        <origin xyz="${optical_offset_x} -${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="$(arg camera_name)_right_camera_optical_frame"/>
    <joint name="$(arg camera_name)_right_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="$(arg camera_name)_right_camera_frame"/>
        <child link="$(arg camera_name)_right_camera_optical_frame"/>
    </joint>

    <xacro:if value="$(arg enable_gnss)">
      <link name="$(arg camera_name)_gnss_link" />
      <joint name="$(arg camera_name)_gnss_joint" type="fixed">
        <parent link="$(arg camera_name)_camera_link"/>
        <child link="$(arg camera_name)_gnss_link"/>
        <xacro:insert_block name="gnss_origin" />
      </joint>
    </xacro:if>

</robot>